spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/expenses
    driverClassName: org.mariadb.jdbc.Driver
    username: tomcat
    password: tomcat

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
server:
  port: 8089

---
spring:
  profiles: development

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

