spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/expenses
    driverClassName: org.mariadb.jdbc.Driver
    username: tomcat
    password: tomcat

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 8089



