spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/expenses
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8089



